services:
  - type: web
    name: Jankenpon
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /icons/**
        name: Cache-Control
        value: public, max-age=31536000 
      - path: /images/**
        name: Cache-Control
        value: public, max-age=31536000 
      - path: /fonts/**
        name: Cache-Control
        value: public, max-age=31536000
      - path: /assets/**
        name: Cache-Control
        value: public, max-age=512000
    routes:
      - type: redirect
        source: /**
        destination: index.html
